theme = "everforest_light_medium"

[editor]
mouse = false
bufferline = "multiple"
true-color = true
color-modes = true
auto-pairs = true
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
render = true
character = "┊" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 0

[editor.whitespace.render]
space = "none"
tab = "all"
nbsp = "none"
nnbsp = "none"
newline = "all"


[editor.whitespace.characters]
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)


[editor.lsp]
display-inlay-hints = true
[editor.inline-diagnostics]
cursor-line = "warning"

# Jump back and forth from G menu
[keys.normal."g"]
j = "jump_backward"
k = "jump_forward"


# Key bindings
[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"

[keys.normal]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"


