[[language]]
name = "yaml"
file-types = ["yml", "yaml", "bu"]

[[language]]
name = "python"

[language-server.pylsp.config.pylsp]
plugins.pylint.enabled = true
plugins.flake8.enabled = true
plugins.pyflakes.enabled = false
plugins.pyls_mypy.enabled = false
plugins.pyls_mypy.live_mode = false
plugins.isort.enabled = false

[[language]]
name = "go"
auto-format = true
[language-server.gopls.config.hints]
assignVariableTypes = true
compositeLiteralFields = true
constantValues = true
functionTypeParameters = true
parameterNames = true
rangeVariableTypes = true

