[[language]]
name = "yaml"
file-types = ["yml", "yaml", "bu"]

[[language]]
name = "python"

[language-server.pylsp.config.pylsp]
plugins.pylint.enabled = true
plugins.flake8.enabled = true
plugins.pyflakes.enabled = false
plugins.pyls_mypy.enabled = false
plugins.pyls_mypy.live_mode = false
plugins.isort.enabled = false

[[language]]
name = "go"
auto-format = true
[language-server.gopls.config.hints]
assignVariableTypes = true
compositeLiteralFields = true
constantValues = true
functionTypeParameters = true
parameterNames = true
rangeVariableTypes = true

[[language]]
name = "json"
language-servers = [{ name = "vscode-json-language-server" }]
#config = { "provideFormatter" = true, "json" = { "keepLines" = { "enable" = true } } }
formatter = { command = 'npx', args = ["prettier", "--parser", "json"] }


[[language-server.vscode-json-language-server.config.json.schemas]]
fileMatch = [ "meta.json", "buildmeta.json", "v1.json" ]
url = "https://raw.githubusercontent.com/coreos/coreos-assembler/refs/heads/main/src/v1.json"

[[language]]
name = "rust"

[language-server.rust-analyzer.config.check]
command = "clippy"
